### ISSUE TITLE
Unreal Engine marketplace to FAB

### ISSUE THREAD

**Issue by JohnathanBurov** [tsdaer/SVG_Support#2]
I am interested in that asset. But can't get it.
![Screenshot from 2024-12-03 22-04-51](https://github.com/user-attachments/assets/8f6ef611-3e55-4c44-91ec-57765e6a1d87)
How to buy it?

**Comment by tsdaer** [comment]
It's free now,[fab](https://fab.com/s/e8bcd1574794)
